version: "3.8"

services:
  bot:
    container_name: bot
    build: .
    depends_on:
      - db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      VK_TOKEN: ${VK_TOKEN}
      VK_ID: ${VK_ID}
      WAIT_IN_MINS: ${WAIT_IN_MINS}
      TIMEZONE: ${TIMEZONE}
    restart: always

  db:
    container_name: db
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ruobr-db
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
